logging:
    file: log.txt
    level:
        org:
            springframework:
                web: info
            hibernate: info
        root: info


management:
    context-path: /management

server:
    port: 12999
    context-path: /

spring:
    application:
        name: kennel api wrapper
    data:
        rest:
            base-path: /api
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./db;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        platform: h2
        initialize: false
    h2:
        console:
            enabled: false
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                show_sql: false
                use_sql_comments: true
                format_sql: true
                type: debug
        hibernate:
            ddl-auto: none